.PHONY: gen test build clean setup format lint release ci-check

gen:
	./tools/gen.sh

test:
	./tools/test.sh

build:
	./tools/build.sh

clean:
	./tools/clean.sh

setup:
	./tools/setup.sh

format:
	./tools/format.sh

lint:
	./tools/lint.sh

release:
	./tools/release.sh

ci-check:
	./tools/ci-check.sh
