default_platform(:android)

platform :android do
  desc "Deploy to Play Store Internal Testing"
  lane :internal do |options|
    flavor = options[:flavor] || "staging"
    upload_to_play_store(
      track: "internal",
      aab: "../build/app/outputs/bundle/#{flavor}Release/app-#{flavor}-release.aab",
      release_status: "completed"
    )
  end

  desc "Upload to Play production as a draft release"
  lane :production do |options|
    flavor = options[:flavor] || "prod"
    upload_to_play_store(
      track: "production",
      aab: "../build/app/outputs/bundle/#{flavor}Release/app-#{flavor}-release.aab",
      release_status: "draft"
    )
  end
end
