default_platform(:ios)

platform :ios do
  desc "Build and deploy to TestFlight"
  lane :beta do
    build_app(
      scheme: "staging",
      export_method: "app-store"
    )
    upload_to_testflight(skip_waiting_for_build_processing: true)
  end

  desc "Deploy to App Store"
  lane :release do
    build_app(
      scheme: "prod",
      export_method: "app-store"
    )
    upload_to_app_store(skip_metadata: true, skip_screenshots: true)
  end
end

platform :android do
  desc "Deploy to Play Store Internal Testing"
  lane :beta do
    upload_to_play_store(
      track: "internal",
      aab: "../build/app/outputs/bundle/stagingRelease/app-staging-release.aab"
    )
  end

  desc "Deploy to Play Store"
  lane :release do
    upload_to_play_store(
      track: "production",
      aab: "../build/app/outputs/bundle/prodRelease/app-prod-release.aab"
    )
  end
end
